# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: cloud-infra-demo

image:
  repository: public.ecr.aws/k0h3x1n2/cloud-infra-demo
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
