---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cloud-infra-demo"
  namespace: "default"
  labels:
    app: cloud-infra-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-infra-demo
  template:
    metadata:
      labels:
        app: cloud-infra-demo
    spec:
      containers:
      - name: "cloud-infra-deployment-1"
        image: "public.ecr.aws/k0h3x1n2/cloud-infra-demo:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "cloud-infra-demo-hpa-cyxd"
  namespace: "default"
  labels:
    app: cloud-infra-demo
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "cloud-infra-demo"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: cloud-infra-demo
  name: cloud-infra-demo-ingress
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30285
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-infra-demo
  sessionAffinity: None
  type: LoadBalancer