apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "deployment.yaml"
- "service.yaml"
images:
- name: "app-image"
  newName: "public.ecr.aws/k0h3x1n2/cloud-infra-deployment"
  newTag: "latest"
namespace: "default"