apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: cloud-infra-demo
  name: cloud-infra-demo-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.128.111
  clusterIPs:
  - 10.103.128.111
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30285
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-infra-demo
  sessionAffinity: None
  type: LoadBalancer
