on: [push]
jobs:
  Build-And-Push-Image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      -
        name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws/k0h3x1n2/cloud-infra-demo
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: demo-app:latest