on: [push]

jobs:
  Build-And-Push-Image:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # -
      #   name: Login to Public ECR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: public.ecr.aws
      # -
        # name: Build and Push
        # uses: docker/build-push-action@v3
        # with:
        #   push: true
        #   tags: ${{env.IMAGE_REPOSITORY}}:${{env.IMAGE_TAG}}
      # -
      #   name: Deploy
      #   uses: bitovi/github-actions-deploy-eks-helm@v1.0.3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     cluster-name: test-cluster
      #     chart-path: chart/
      #     config-files: chart/values.yaml
      #     namespace: cloud-infra-demo
      -
        name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}
      - 
        name: Configure Docker/GCloud integration
        run: |-
          gcloud --quiet auth configure-docker
      -
        name: Configure GCloud Authentication
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: test-cluster
          location: us-east1
          credentials: ${{ secrets.GKE_SA_KEY }}
      -
        name: Checkout codebase
        uses: actions/checkout@v3
      # -
      #   name: Configure Kustomize
      #   working-directory: kustomize
      #   run: |-
      #     curl -sfLo kustomize.tar https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz
      #     tar -xzf kustomize.tar -C .
      #     chmod u+x ./kustomize
      # -
      #   name: Deploy Image to Cluster
      #   working-directory: kustomize
      #   run: |-
      #     # ./kustomize edit set image app-image=public.ecr.aws/k0h3x1n2/cloud-infra-deployment:latest
      #     # ./kustomize build . | kubectl apply -f -
      #     kubectl apply -f -
      #     kubectl rollout status deployment/cloud-infra-demo
      #     kubectl get services -o wide
      -
        name: Deploy Image to Cluster
        working-directory: kustomize
        run: |-
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/cloud-infra-demo
          kubectl get services -o wide